### ISSUE TITLE
Shortcuts on SMD Pads

### ISSUE THREAD

**Issue by martin-at-schorsch** [OfItselfSo/LineGrinder#3]
I tried Linegrinder for the first time, and it looks handy. Especially the manual drill touchdown is a very clever feature.
I used Eagle and the PCB Milling ULP before but switched now to KiCad with the need for Gcode generation.

I encounter issues with SMD pads that are shortcuts in the code.

Gerber View:
![2023-05-27 22_15_40-Line Grinder](https://github.com/OfItselfSo/LineGrinder/assets/8039559/02e93d8a-562c-4eae-be7a-f718ad31f0e3)

Generated GCode:
![2023-05-27 22_15_05-Line Grinder](https://github.com/OfItselfSo/LineGrinder/assets/8039559/5aa4a561-6e17-41c7-babb-2025caeb6634)

I noticed some touchdowns I have no idea why it is generated.

Overlayed Gcode with Gerber showing the shortcuts:
![2023-05-27 22_24_17-Line Grinder](https://github.com/OfItselfSo/LineGrinder/assets/8039559/abfbc367-7d41-4ea5-ae0a-073e5e74a40f)

I tried to change some settings in LineGrinder to workaround the issue without luck.
Also, I tried the Kicad Gerber Export with and without X2 Format enabled.

[carrier-ac-wifi_gerber_gcode.zip](https://github.com/OfItselfSo/LineGrinder/files/11582964/carrier-ac-wifi_gerber_gcode.zip)

**Comment by OfItselfSo** [comment]
The dots that look like pad touchdowns appear to be artifacts of the copper pour or copper fill on your PCB. They appear even with pad touchdowns disabled. There are many complex gerber operations going on in a copper pour - including the erasure of lines already drawn (gerber can do that) and it appears to be confusing LineGrinder. The isolation algorythm is always an approximation and rounding errors could leave little dots. The copper pour is not needed for isolations PCB's anyways and the conversion will execute much, much faster without it.

As for the shortcuts (the broken traces). This is clearly a problem but I cannot easily diagnose this because of all the copper fill complexity in the gerber file. Can you please generate a .gbr file without the copper fill and if the problem still exists post the new file here and I will work on it.

**Comment by martin-at-schorsch** [comment]
I removed the fill, and the "deformed pads" remain. The SMD shortcut is gone, but some are still on the two left connectors. BTW: I just noticed that the manual drill dot is missing there, these are thru hole pads.

The layout is different from the version from yesterday as I did not version it properly. Shame on me...

![2023-05-28 21_44_10-Line Grinder](https://github.com/OfItselfSo/LineGrinder/assets/8039559/aa47e8f2-75d9-496e-afd4-6a62b2dcea7e)
![2023-05-28 21_44_37-Line Grinder](https://github.com/OfItselfSo/LineGrinder/assets/8039559/a98a4e9a-b955-48bd-bbc9-44e79803e05c)

Gerber (not functional), including the KiCad 7 PCB in case you would like to tinker around yourself: 

[gerber-test-linegrinder-test-not-functional.zip](https://github.com/OfItselfSo/LineGrinder/files/11585551/gerber-test-linegrinder-test-not-functional.zip)

**Comment by OfItselfSo** [comment]
The SMD pad issue is definitely a bug - a quite tricky one. I can reproduce it and am working on it. It might take a few more days.

**Comment by OfItselfSo** [comment]
A fix for this bug has now been released in version 03.02. You can clone the source and compile it yourself or download the already compiled 03.02 binary from the website at [http://www.ofitselfso.com/LineGrinder/LineGrinder.php](http://www.ofitselfso.com/LineGrinder/LineGrinder.php)

I have tested it on the files you sent and it seems to cure all of the SMD shortcut problems you observed. Thank you very much for you comprehensive and detailed bug report.

Please do let me know if this new release fixes the issue for you.

**Comment by martin-at-schorsch** [comment]
You are right; the original problem is fixed, but a new one surfaced with default settings:
![image](https://github.com/OfItselfSo/LineGrinder/assets/8039559/07a65b12-25e4-4609-bc46-bc90891005fe)

When increasing the "IsoCutWidth" to 0,4mm (~0,015 inch) it looks okay:
![image](https://github.com/OfItselfSo/LineGrinder/assets/8039559/0c661e20-cd91-42f3-ab07-82e2c9746265)

The issue with enabling "IsoPadTouchDownsWanted" and the ignored rectangular pads remains not matter of the cut width:
![image](https://github.com/OfItselfSo/LineGrinder/assets/8039559/60d63735-dbcc-4aa4-9159-e861e119f15f)

**Comment by OfItselfSo** [comment]
The lack of pad touchdowns on the SMD pads is caused by the fact that they are Macros not simple apertures. The Gerber spec only has a few primitive objects - circle, oval, rectangle etc as apertures. These are "flashed" to produce a pad. More complex objects such as a rectangle with rounded corners (an SMD pad) is created by flashing multiple smaller primitive objects (four circles for the corners and then some rectangles to fill in the sides). Because they are composed of multiple objects, macros do not really have an consistent center point onto which a pad touchdown could be placed. I know the center of the SMD pad looks obvious to the eye but in the code the actual Macro origin could be pretty much anywhere and the primitives offset from that. Also there are rotations and transparencies to consider. The upshot is that it is very difficult to calculate the center of a macro in the general case and it essentially means finding the center of an area of a complex arbitrary number of graphical objects. 

If a touchdown is needed on an object derived from a macro then simply placing a smaller simple hidden circular pad on or under it should generate a pad touchdown in the code and leave the Gerber traces unchanged. If this is not satisfactory please tell me a bit more about your specific use case and I will see what I can do.

The little gap is a tricky one. I have traced it down in the code and it is derived from rounding errors. LineGrinder maps all of the Gerber objects onto a grid and grids are essentially integer based. This means means things like radiuses of circles etc get rounded to the nearest grid point (like pixels on a screen). The gap is due to the grid you are using not being fine enough - LineGrinder simply does not see an intersection between the circle primitive and vector line part of the SMD macro at that point on the grid. 

Fortunately this has an easy fix. Look at the top of the Settings tab. Change the "isoplot points per mm" to about 150 it is probably at the default of 78 now. This increases the number of points on the grid and essentially everything is mapped at a finer resolution reducing the rounding errors. There are some issues in here - you can change the "isoplot points per mm" setting and just open the Gerber file. However, if you change from inches to mm (or back) you need to drop and recreate your File Managers before opening the file. This awkwardness is actually Issue #2 and that whole mechanism will be cleaned up eventually.

**Comment by martin-at-schorsch** [comment]
I can confirm setting "isoplot points per mm" to 150 solves the issue.

Regarding the touchdowns, I changed the pad type to the one that works.

Thx for your quick support and detailed explanations.
